DROP TABLE IF EXISTS Com;

CREATE TABLE Com (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    comment TEXT NOT NULL
);

